version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--log.level=error"
    ports:
      - "9090:9090"
    networks:
      - global_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
      - loki
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ../../../persistentdata/grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOG_LEVEL=error
    networks:
      - global_net

  loki:
    image: grafana/loki:latest
    container_name: loki
    command:
      - -config.file=/etc/loki/config.yml
      - -log.level=error
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml:ro
      - ../../../persistentdata/loki/data:/var/loki
      - ../../../persistentdata/loki/wal:/wal
    ports:
      - "3100:3100"
    networks:
      - global_net

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    command:
      - "-config.file=/etc/promtail/config.yml"
      - "-log.level=error"
    ports:
      - "9080:9080"
    networks:
      - global_net
    privileged: true


volumes:
  grafana_data:
  loki_data:

networks:
  global_net:
    external: true
