x-service-defaults: &service_defaults
  restart: unless-stopped
  networks:
    - global_net

x-pgbouncer-volumes: &pgbouncer_volumes
  - ../pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
  - ../pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro

services:
  postgres:
    <<: *service_defaults
    image: postgres:15.3
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgbouncer:
    <<: *service_defaults
    image: edoburu/pgbouncer:v1.24.1-p1
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "6432:6432"
    volumes: *pgbouncer_volumes
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h 127.0.0.1 -p 6432 -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
